[package]
name = "scidtopgn"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Library for reading and writing SCID chess databases"
keywords = ["chess", "pgn", "database", "scid"]
categories = ["parser-implementations", "game-development"]

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
pretty_assertions = "1.4"
tempfile = "3"
